/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocalculadora;

/**
 *
 * @author bruno
 */
public class InterfazGraficaCalculadora extends javax.swing.JFrame {
    private Calculadora calc;
    private String res;
    private String[] arr;
    private boolean operadores;
    private boolean parentesisA;
    private boolean parentesisC;
    private boolean num;
    private boolean var;
    private boolean punto;
    private boolean neg;
    
    /**
     * Creates new form Calculadoras
     */
    public InterfazGraficaCalculadora() {
        initComponents();
        calc = new Calculadora();
        operadores = false;
        parentesisA = true;
        parentesisC = false;
        num = true;
        var = true;
        punto = true;
        neg = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j8Button = new javax.swing.JButton();
        jParentesisD = new javax.swing.JButton();
        j2Button = new javax.swing.JButton();
        jVarX = new javax.swing.JButton();
        j1Button = new javax.swing.JButton();
        jVarZ = new javax.swing.JButton();
        jSuma = new javax.swing.JButton();
        jVarY = new javax.swing.JButton();
        jEqu = new javax.swing.JButton();
        jRes = new javax.swing.JButton();
        jMulti = new javax.swing.JButton();
        jDiv = new javax.swing.JButton();
        jPow = new javax.swing.JButton();
        jPantalla = new javax.swing.JTextField();
        j4Button = new javax.swing.JButton();
        j7Button = new javax.swing.JButton();
        j6Button = new javax.swing.JButton();
        j3Button = new javax.swing.JButton();
        j0Button = new javax.swing.JButton();
        j5Button = new javax.swing.JButton();
        jPunto = new javax.swing.JButton();
        jC = new javax.swing.JButton();
        j9Button = new javax.swing.JButton();
        jParentesisI = new javax.swing.JButton();
        jNegativo = new javax.swing.JButton();
        jEvalVar = new javax.swing.JButton();
        jYLabel = new javax.swing.JLabel();
        jXLabel1 = new javax.swing.JLabel();
        jZLabel2 = new javax.swing.JLabel();
        jXTxt = new javax.swing.JTextField();
        jYTxt = new javax.swing.JTextField();
        jZTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j8Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j8Button.setText("8");
        j8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ButtonActionPerformed(evt);
            }
        });

        jParentesisD.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jParentesisD.setText(")");
        jParentesisD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jParentesisDActionPerformed(evt);
            }
        });

        j2Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j2Button.setText("2");
        j2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ButtonActionPerformed(evt);
            }
        });

        jVarX.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jVarX.setText("x");
        jVarX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVarXActionPerformed(evt);
            }
        });

        j1Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j1Button.setText("1");
        j1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ButtonActionPerformed(evt);
            }
        });

        jVarZ.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jVarZ.setText("z");
        jVarZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVarZActionPerformed(evt);
            }
        });

        jSuma.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSuma.setText("+");
        jSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumaActionPerformed(evt);
            }
        });

        jVarY.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jVarY.setText("y");
        jVarY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVarYActionPerformed(evt);
            }
        });

        jEqu.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jEqu.setText("=");
        jEqu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEquActionPerformed(evt);
            }
        });

        jRes.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jRes.setText("-");
        jRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResActionPerformed(evt);
            }
        });

        jMulti.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jMulti.setText("*");
        jMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiActionPerformed(evt);
            }
        });

        jDiv.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jDiv.setText("/");
        jDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivActionPerformed(evt);
            }
        });

        jPow.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPow.setText("^");
        jPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowActionPerformed(evt);
            }
        });

        jPantalla.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jPantalla.setFocusTraversalPolicyProvider(true);
        jPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPantallaActionPerformed(evt);
            }
        });

        j4Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j4Button.setText("4");
        j4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ButtonActionPerformed(evt);
            }
        });

        j7Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j7Button.setText("7");
        j7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ButtonActionPerformed(evt);
            }
        });

        j6Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j6Button.setText("6");
        j6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ButtonActionPerformed(evt);
            }
        });

        j3Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j3Button.setText("3");
        j3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ButtonActionPerformed(evt);
            }
        });

        j0Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j0Button.setText("0");
        j0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0ButtonActionPerformed(evt);
            }
        });

        j5Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j5Button.setText("5");
        j5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ButtonActionPerformed(evt);
            }
        });

        jPunto.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPunto.setText(".");
        jPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPuntoActionPerformed(evt);
            }
        });

        jC.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jC.setText("C");
        jC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCActionPerformed(evt);
            }
        });

        j9Button.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        j9Button.setText("9");
        j9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ButtonActionPerformed(evt);
            }
        });

        jParentesisI.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jParentesisI.setText("(");
        jParentesisI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jParentesisIActionPerformed(evt);
            }
        });

        jNegativo.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jNegativo.setText("+/-");
        jNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNegativoActionPerformed(evt);
            }
        });

        jEvalVar.setText("Evaluar");
        jEvalVar.setEnabled(false);
        jEvalVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEvalVarActionPerformed(evt);
            }
        });

        jYLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jYLabel.setText("y:");

        jXLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jXLabel1.setText("x:");

        jZLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jZLabel2.setText("z:");

        jXTxt.setEnabled(false);

        jYTxt.setEnabled(false);

        jZTxt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPantalla)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(j0Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(j1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEqu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jParentesisI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jParentesisD)
                            .addGap(18, 18, 18)
                            .addComponent(jVarX)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jVarY)
                            .addGap(18, 18, 18)
                            .addComponent(jVarZ)
                            .addGap(18, 18, 18)
                            .addComponent(jNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(j7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(j8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(j9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jEvalVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jYLabel)
                                        .addComponent(jXLabel1)
                                        .addComponent(jZLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jXTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jZTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jYTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPow, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jParentesisI, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jParentesisD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jVarX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jVarY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jVarZ, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j9Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPow, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(j0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jEqu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jEvalVar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jYTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jZLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jZTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jNegativo.getAccessibleContext().setAccessibleName("");
        jEvalVar.getAccessibleContext().setAccessibleName("Evalúa");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0ButtonActionPerformed
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(0));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j0ButtonActionPerformed

    private void j1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(1));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j1ButtonActionPerformed

    private void j2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(2));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j2ButtonActionPerformed

    private void j3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(3));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j3ButtonActionPerformed

    private void j4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(4));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j4ButtonActionPerformed

    private void j5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(5));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j5ButtonActionPerformed

    private void j6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(6));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j6ButtonActionPerformed

    private void j7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(7));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j7ButtonActionPerformed

    private void j8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(8));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j8ButtonActionPerformed

    private void j9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ButtonActionPerformed
        
        if(num){
            jPantalla.setText(jPantalla.getText()+String.valueOf(9));
            jEqu.setEnabled(true);
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            var = false;
            neg = false;
        }
    }//GEN-LAST:event_j9ButtonActionPerformed

    private void jCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCActionPerformed
        jPantalla.setText("");
        jEqu.setEnabled(true);
        //Restaura los valores iniciales de las variables y sus jTextField
        jXTxt.setEnabled(false);
        jYTxt.setEnabled(false);
        jZTxt.setEnabled(false);
        jEvalVar.setEnabled(false);
        operadores = false;
        parentesisA = true;
        parentesisC = false;
        num = true;
        var = true;
        punto = true;
        neg = true;
    }//GEN-LAST:event_jCActionPerformed

    private void jSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumaActionPerformed
            if(operadores){
                jPantalla.setText(jPantalla.getText()+" + ");
                jEqu.setEnabled(false);
                operadores = false;
                parentesisA = true;
                parentesisC = false;
                num = true;
                var = true;
                punto = true;
                neg = true;
            }
    }//GEN-LAST:event_jSumaActionPerformed

    private void jResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResActionPerformed

            if(operadores){
                jPantalla.setText(jPantalla.getText()+" - ");
                jEqu.setEnabled(false);
                operadores = false;
                parentesisA = true;
                parentesisC = false;
                num = true;
                var = true;
                punto = true;
                neg = true;
            }
    }//GEN-LAST:event_jResActionPerformed

    private void jPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowActionPerformed

            if(operadores){
                jPantalla.setText(jPantalla.getText()+" ^ ");
                jEqu.setEnabled(false);
                operadores = false;
                parentesisA = true;
                parentesisC = false;
                num = true;
                var = true;
                punto = true;
                neg = true;
            }
    }//GEN-LAST:event_jPowActionPerformed

    private void jMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiActionPerformed

            if(operadores){
                jPantalla.setText(jPantalla.getText()+" * ");
                jEqu.setEnabled(false);
                operadores = false;
                parentesisA = true;
                parentesisC = false;
                num = true;
                var = true;
                punto = true;
                neg = true;
            }
    }//GEN-LAST:event_jMultiActionPerformed

    private void jDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivActionPerformed
        
        if(operadores){
                jPantalla.setText(jPantalla.getText()+" / ");
                jEqu.setEnabled(false);
                operadores = false;
                parentesisA = true;
                parentesisC = false;
                num = true;
                var = true;
                punto = true;
                neg = true;
            }
    }//GEN-LAST:event_jDivActionPerformed

    private void jParentesisIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jParentesisIActionPerformed
        if(parentesisA){
            String exp = jPantalla.getText();
            int len = exp.length();
            
            if(!exp.isEmpty() && exp.charAt(len-1) == '-')
                jPantalla.setText(jPantalla.getText() + "1 * "+ "( ");
            else
                jPantalla.setText(jPantalla.getText()+ "( ");
            operadores = false;
            }
    }//GEN-LAST:event_jParentesisIActionPerformed

    private void jParentesisDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jParentesisDActionPerformed

        if(parentesisC){
            jPantalla.setText(jPantalla.getText()+" )");
            num = false;
            var = false;
        }
    }//GEN-LAST:event_jParentesisDActionPerformed

    private void jNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNegativoActionPerformed
        if(neg){
            jPantalla.setText(jPantalla.getText()+'-');
            neg = false;
        }
    }//GEN-LAST:event_jNegativoActionPerformed

    private void jPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPuntoActionPerformed
        if(punto){
            jPantalla.setText(jPantalla.getText()+'.');
            punto = false;
        }
    }//GEN-LAST:event_jPuntoActionPerformed

    private void jEquActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEquActionPerformed

        try{
            //Toma el texto en pantalla
            res = jPantalla.getText();
            //Separa la cadena para que pueda analizarse
            arr = calc.separador(res);
            //Evalua usando la calculadora
            res = calc.evalua(arr);
            //Pone el texto correcto en pantalla
            jPantalla.setText(res);
            //Restaura los valores iniciales de las variables y sus jTextField
            jXTxt.setEnabled(false);
            jYTxt.setEnabled(false);
            jZTxt.setEnabled(false);
            jEvalVar.setEnabled(false);
            punto = false;
        } 
        catch(Exception e){
            jPantalla.setText("Syntax error");
        }
        
    }//GEN-LAST:event_jEquActionPerformed

    private void jVarYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVarYActionPerformed
        if(var){
            jEvalVar.setEnabled(true);
            jYTxt.setEnabled(true);
            jEqu.setEnabled(false);
            jPantalla.setText(jPantalla.getText()+"y");
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            num = false;
            var = false;
        }
    }//GEN-LAST:event_jVarYActionPerformed

    private void jVarXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVarXActionPerformed
        if(var){
            jEvalVar.setEnabled(true);
            jXTxt.setEnabled(true);
            jEqu.setEnabled(false);
            jPantalla.setText(jPantalla.getText()+"x");
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            num = false;
            var = false;
        }
    }//GEN-LAST:event_jVarXActionPerformed

    private void jVarZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVarZActionPerformed
        if(var){
            jEvalVar.setEnabled(true);
            jZTxt.setEnabled(true);
            jEqu.setEnabled(false);
            jPantalla.setText(jPantalla.getText()+"z");
            operadores = true;
            parentesisA = false;
            parentesisC = true;
            num = false;
            var = false;
        }
    }//GEN-LAST:event_jVarZActionPerformed

    private void jEvalVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEvalVarActionPerformed
        String cad;
        String x,y,z;
        
        try{
            x=jXTxt.getText();
            y=jYTxt.getText();
            z=jZTxt.getText();
            //Toma el texto de la pantalla
            cad=jPantalla.getText();
            //Asigna las variables x, y, z en la expresión
            arr=calc.asigVar(cad, x, y, z);
            //Evalúa con los valores dados
            res = calc.evalua(arr);
            //Regresa el valor total a la pantalla
            jPantalla.setText(res);

            //Regresa los Botones y Labels a su estado inicial.
            jEqu.setEnabled(true);
            jEvalVar.setEnabled(false);
            jXTxt.setEnabled(false);
            jXTxt.setText("");
            jYTxt.setEnabled(false);
            jYTxt.setText("");
            jZTxt.setEnabled(false);
            jZTxt.setText("");
            punto = false;
            neg = false;
        }
        catch(NumberFormatException e){
            jPantalla.setText("Entrada inválida");
        }
    }//GEN-LAST:event_jEvalVarActionPerformed

    private void jPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPantallaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j0Button;
    private javax.swing.JButton j1Button;
    private javax.swing.JButton j2Button;
    private javax.swing.JButton j3Button;
    private javax.swing.JButton j4Button;
    private javax.swing.JButton j5Button;
    private javax.swing.JButton j6Button;
    private javax.swing.JButton j7Button;
    private javax.swing.JButton j8Button;
    private javax.swing.JButton j9Button;
    private javax.swing.JButton jC;
    private javax.swing.JButton jDiv;
    private javax.swing.JButton jEqu;
    private javax.swing.JButton jEvalVar;
    private javax.swing.JButton jMulti;
    private javax.swing.JButton jNegativo;
    private javax.swing.JTextField jPantalla;
    private javax.swing.JButton jParentesisD;
    private javax.swing.JButton jParentesisI;
    private javax.swing.JButton jPow;
    private javax.swing.JButton jPunto;
    private javax.swing.JButton jRes;
    private javax.swing.JButton jSuma;
    private javax.swing.JButton jVarX;
    private javax.swing.JButton jVarY;
    private javax.swing.JButton jVarZ;
    private javax.swing.JLabel jXLabel1;
    private javax.swing.JTextField jXTxt;
    private javax.swing.JLabel jYLabel;
    private javax.swing.JTextField jYTxt;
    private javax.swing.JLabel jZLabel2;
    private javax.swing.JTextField jZTxt;
    // End of variables declaration//GEN-END:variables

}
